liu_river_final_project/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView, TemplateView
from proleague.views import SignUp

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('proleague.urls')),

    path(
        '',
        RedirectView.as_view(
            pattern_name='about_urlpattern',
            permanent=False
        )
    ),

    path(
        'login/',
        LoginView.as_view(template_name='proleague/login.html'),
        name='login_urlpattern'
    ),

    path(
        'signup/',
        SignUp.as_view(),
        name='signup_urlpattern'
    ),

    path(
        'logout/',
        LogoutView.as_view(),
        name='logout_urlpattern'
    ),

    path(
        'password_change/',
        PasswordChangeView.as_view(
            success_url=reverse_lazy('password_change_done_urlpattern'),
            template_name='proleague/password_change_form.html'),
        name='password_change_urlpattern'
    ),

    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='proleague/password_change_done.html'
        ),
        name='password_change_done_urlpattern'
    ),

    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='proleague/password_reset_form.html',
            email_template_name='proleague/password_reset_email.html'
        ),
        name='password_reset_urlpattern'
    ),

    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='proleague/password_reset_done.html'
        ),
        name='password_reset_done'
    ),

    path(
        'password_reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='proleague/password_reset_confirm.html',
        ),
        name='password_reset_confirm'
    ),

    path(
        'password_reset/complete/',
        PasswordResetCompleteView.as_view(
            template_name='proleague/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),

    path(
        'about/',
        TemplateView.as_view(template_name='proleague/about.html'),
        name='about_urlpattern'
    ),
]

proleague/urls.py
from django.urls import path

from .views import (
    TournamentList, TournamentCreate, TournamentDelete, TournamentDetail, TournamentUpdate,
    GameList, GameCreate, GameDelete, GameDetail, GameUpdate,
    PlayerList, PlayerCreate, PlayerDelete, PlayerDetail, PlayerUpdate, PlayerSearch,
    MatchList, MatchCreate, MatchDelete, MatchDetail, MatchUpdate, MatchSearch,
    TeamList, TeamCreate, TeamDelete, TeamDetail, TeamUpdate, TeamSearch,
    SchoolList, SchoolCreate, SchoolDelete, SchoolDetail, SchoolUpdate
)


urlpatterns = [
    path(
        'tournament/',
        TournamentList.as_view(),
        name='proleague_tournament_list_urlpattern'
    ),

    path(
        'tournament/<int:pk>/',
        TournamentDetail.as_view(),
        name='proleague_tournament_detail_urlpattern'
    ),

    path(
        'tournament/create/',
        TournamentCreate.as_view(),
        name='proleague_tournament_create_urlpattern'
    ),

    path(
        'tournament/<int:pk>/update/',
        TournamentUpdate.as_view(),
        name='proleague_tournament_update_urlpattern'
    ),

    path(
        'tournament/<int:pk>/delete/',
        TournamentDelete.as_view(),
        name='proleague_tournament_delete_urlpattern'
    ),

    path(
        'game/',
        GameList.as_view(),
        name='proleague_game_list_urlpattern'
    ),

    path(
        'game/<int:pk>/',
        GameDetail.as_view(),
        name='proleague_game_detail_urlpattern'
    ),

    path(
        'game/create/',
        GameCreate.as_view(),
        name='proleague_game_create_urlpattern'
    ),

    path(
        'game/<int:pk>/update/',
        GameUpdate.as_view(),
        name='proleague_game_update_urlpattern'
    ),

    path(
        'game/<int:pk>/delete/',
        GameDelete.as_view(),
        name='proleague_game_delete_urlpattern'
    ),

    path(
        'player/',
        PlayerList.as_view(),
        name='proleague_player_list_urlpattern'
    ),

    path(
        'player/<int:pk>/',
        PlayerDetail.as_view(),
        name='proleague_player_detail_urlpattern'
    ),

    path(
        'player/create/',
        PlayerCreate.as_view(),
        name='proleague_player_create_urlpattern'
    ),

    path(
        'player/<int:pk>/update/',
        PlayerUpdate.as_view(),
        name='proleague_player_update_urlpattern'
    ),

    path(
        'player/<int:pk>/delete/',
        PlayerDelete.as_view(),
        name='proleague_player_delete_urlpattern'
    ),

    path(
        'player/search/',
        PlayerSearch.as_view(),
        name='proleague_player_search_urlpattern'
    ),

    path(
        'match/',
        MatchList.as_view(),
        name='proleague_match_list_urlpattern'
    ),

    path(
        'match/<int:pk>/',
        MatchDetail.as_view(),
        name='proleague_match_detail_urlpattern'
    ),

    path(
        'match/create/',
        MatchCreate.as_view(),
        name='proleague_match_create_urlpattern'
    ),

    path(
        'match/<int:pk>/update/',
        MatchUpdate.as_view(),
        name='proleague_match_update_urlpattern'
    ),

    path(
        'match/<int:pk>/delete/',
        MatchDelete.as_view(),
        name='proleague_match_delete_urlpattern'
    ),

    path(
        'match/search/',
        MatchSearch.as_view(),
        name='proleague_match_search_urlpattern'
    ),

    path(
        'team/',
        TeamList.as_view(),
        name='proleague_team_list_urlpattern'
    ),

    path(
        'team/<int:pk>/',
        TeamDetail.as_view(),
        name='proleague_team_detail_urlpattern'
    ),

    path(
        'team/create/',
        TeamCreate.as_view(),
        name='proleague_team_create_urlpattern'
    ),

    path(
        'team/<int:pk>/update/',
        TeamUpdate.as_view(),
        name='proleague_team_update_urlpattern'
    ),

    path(
        'team/<int:pk>/delete/',
        TeamDelete.as_view(),
        name='proleague_team_delete_urlpattern'
    ),

    path(
        'team/search/',
        TeamSearch.as_view(),
        name='proleague_team_search_urlpattern'
    ),

    path(
        'school/',
        SchoolList.as_view(),
        name='proleague_school_list_urlpattern'
    ),

    path(
        'school/<int:pk>/',
        SchoolDetail.as_view(),
        name='proleague_school_detail_urlpattern'
    ),

    path(
        'school/create/',
        SchoolCreate.as_view(),
        name='proleague_school_create_urlpattern'
    ),

    path(
        'school/<int:pk>/update/',
        SchoolUpdate.as_view(),
        name='proleague_school_update_urlpattern'
    ),

    path(
        'school/<int:pk>/delete/',
        SchoolDelete.as_view(),
        name='proleague_school_delete_urlpattern'
    ),
]

proleague/models.py
from django.db import models
from django.db.models import UniqueConstraint
from django.urls import reverse


class Period(models.Model):
    period_id = models.AutoField(primary_key=True)
    period_sequence = models.IntegerField(unique=True)
    period_name = models.CharField(max_length=45, unique=True)

    def __str__(self):
        return f'{self.period_name}'

    class Meta:
        ordering = ['period_sequence']


class Year(models.Model):
    year_id = models.AutoField(primary_key=True)
    year = models.IntegerField(unique=True)

    def __str__(self):
        return f'{self.year}'

    class Meta:
        ordering = ['year']


class Position(models.Model):
    position_id = models.AutoField(primary_key=True)
    position_sequence = models.IntegerField(unique=True)
    position_name = models.CharField(max_length=45, unique=True)

    def __str__(self):
        return f'{self.position_name}'

    class Meta:
        ordering = ['position_sequence']


class Game(models.Model):
    game_id = models.AutoField(primary_key=True)
    game_name = models.CharField(max_length=100)
    website = models.CharField(max_length=255, default='')
    developer = models.CharField(max_length=100, default='')
    developer_website = models.CharField(max_length=255, default='')
    genre = models.CharField(max_length=45)

    def __str__(self):
        return f'{self.game_name}'

    def get_absolute_url(self):
        return reverse(
            'proleague_game_detail_urlpattern',
            kwargs={'pk': self.pk}
        )

    def get_update_url(self):
        return reverse(
            'proleague_game_update_urlpattern',
            kwargs={'pk': self.pk}
        )

    def get_delete_url(self):
        return reverse(
            'proleague_game_delete_urlpattern',
            kwargs={'pk': self.pk}
        )

    class Meta:
        ordering = ['game_name']
        constraints = [
            UniqueConstraint(fields=['game_name', 'genre'], name='unique_game')
        ]


class Tournament(models.Model):
    tournament_id = models.AutoField(primary_key=True)
    tournament_name = models.CharField(max_length=255)
    start_date = models.DateField()
    end_date = models.DateField()
    year = models.ForeignKey(Year, related_name='tournaments', on_delete=models.PROTECT)
    period = models.ForeignKey(Period, related_name='tournaments', on_delete=models.PROTECT)
    game = models.ForeignKey(Game, related_name='tournaments', on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.tournament_name}'

    def get_absolute_url(self):
        return reverse(
            'proleague_tournament_detail_urlpattern',
            kwargs={'pk': self.pk}
        )

    def get_update_url(self):
        return reverse(
            'proleague_tournament_update_urlpattern',
            kwargs={'pk': self.pk}
        )

    def get_delete_url(self):
        return reverse(
            'proleague_tournament_delete_urlpattern',
            kwargs={'pk': self.pk}
        )

    class Meta:
        ordering = ['year__year', 'period__period_sequence', 'start_date', 'end_date']
        constraints = [
            UniqueConstraint(fields=['year', 'period', 'tournament_name'], name='unique_tournament')
        ]


class Team(models.Model):
    team_id = models.AutoField(primary_key=True)
    team_name = models.CharField(max_length=45)
    acronym = models.CharField(max_length=45, unique=True)
    tournament = models.ForeignKey(Tournament, related_name='teams', on_delete=models.PROTECT)
    position = models.ForeignKey(
        Position, related_name='teams', on_delete=models.PROTECT, null=True, blank=True
    )

    def __str__(self):
        return f'{self.team_name} ({self.acronym})'

    def get_absolute_url(self):
        return reverse(
            'proleague_team_detail_urlpattern',
            kwargs={'pk': self.pk}
        )

    def get_update_url(self):
        return reverse(
            'proleague_team_update_urlpattern',
            kwargs={'pk': self.pk}
        )

    def get_delete_url(self):
        return reverse(
            'proleague_team_delete_urlpattern',
            kwargs={'pk': self.pk}
        )

    class Meta:
        ordering = ['team_name']
        constraints = [
            UniqueConstraint(fields=['team_name', 'tournament'], name='unique_team')
        ]


class Match(models.Model):
    match_id = models.AutoField(primary_key=True)
    match_type = models.CharField(max_length=100)
    match_time = models.DateTimeField()
    duration = models.CharField(max_length=45)
    team_a = models.ForeignKey(Team, related_name='match_a', on_delete=models.PROTECT)
    team_b = models.ForeignKey(Team, related_name='match_b', on_delete=models.PROTECT)
    match_detail = models.TextField()
    video_link = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.team_a.tournament} - [{self.match_type}] {self.team_a.acronym} VS. {self.team_b.acronym}'

    def get_absolute_url(self):
        return reverse(
            'proleague_match_detail_urlpattern',
            kwargs={'pk': self.pk}
        )

    def get_update_url(self):
        return reverse(
            'proleague_match_update_urlpattern',
            kwargs={'pk': self.pk}
        )

    def get_delete_url(self):
        return reverse(
            'proleague_match_delete_urlpattern',
            kwargs={'pk': self.pk}
        )

    class Meta:
        ordering = ['team_a__tournament', 'match_time']
        constraints = [
            UniqueConstraint(fields=['match_type', 'team_a', 'team_b'], name='unique_match')
        ]


class School(models.Model):
    school_id = models.AutoField(primary_key=True)
    school_name = models.CharField(max_length=255)
    city = models.CharField(max_length=45)
    state = models.CharField(max_length=45)

    def __str__(self):
        return f'{self.school_name}'

    def get_absolute_url(self):
        return reverse(
            'proleague_school_detail_urlpattern',
            kwargs={'pk': self.pk}
        )

    def get_update_url(self):
        return reverse(
            'proleague_school_update_urlpattern',
            kwargs={'pk': self.pk}
        )

    def get_delete_url(self):
        return reverse(
            'proleague_school_delete_urlpattern',
            kwargs={'pk': self.pk}
        )

    class Meta:
        ordering = ['school_name']
        constraints = [
            UniqueConstraint(fields=['school_name', 'city', 'state'], name='unique_school')
        ]


class Player(models.Model):
    player_id = models.AutoField(primary_key=True)
    player_name = models.CharField(max_length=100)
    email = models.CharField(max_length=255)
    gamer_tag = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=45)
    school = models.ForeignKey(School, related_name='players', on_delete=models.PROTECT)
    team = models.ForeignKey(Team, related_name='players', on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.player_name} ({self.gamer_tag})'

    def get_absolute_url(self):
        return reverse(
            'proleague_player_detail_urlpattern',
            kwargs={'pk': self.pk}
        )

    def get_update_url(self):
        return reverse(
            'proleague_player_update_urlpattern',
            kwargs={'pk': self.pk}
        )

    def get_delete_url(self):
        return reverse(
            'proleague_player_delete_urlpattern',
            kwargs={'pk': self.pk}
        )

    class Meta:
        ordering = ['player_name', 'gamer_tag']
        constraints = [
            UniqueConstraint(fields=['player_name', 'gamer_tag'], name='unique_player')
        ]

proleague/forms.py
from django import forms

from .models import Tournament, Match, Player, Team, Game, School


class TournamentForm(forms.ModelForm):
    class Meta:
        model = Tournament
        fields = '__all__'

    def clean_tournament_name(self):
        return self.cleaned_data['tournament_name'].strip()


class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = '__all__'

    def clean_game_name(self):
        return self.cleaned_data['game_name'].strip()

    def clean_website(self):
        return self.cleaned_data['website'].strip()

    def clean_developer(self):
        return self.cleaned_data['developer'].strip()

    def clean_developer_website(self):
        return self.cleaned_data['developer_website'].strip()

    def clean_genre(self):
        return self.cleaned_data['genre'].strip()


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = '__all__'

    def clean_team_name(self):
        return self.cleaned_data['team_name'].strip()

    def clean_acronym(self):
        return self.cleaned_data['acronym'].strip()


class MatchForm(forms.ModelForm):
    class Meta:
        model = Match
        fields = '__all__'

    def clean_match_type(self):
        return self.cleaned_data['match_type'].strip()

    def clean_video_link(self):
        return self.cleaned_data['video_link'].strip()


class SchoolForm(forms.ModelForm):
    class Meta:
        model = School
        fields = '__all__'

    def clean_school_name(self):
        return self.cleaned_data['school_name'].strip()

    def clean_city(self):
        return self.cleaned_data['city'].strip()

    def clean_state(self):
        return self.cleaned_data['state'].strip()


class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = '__all__'

    def clean_player_name(self):
        return self.cleaned_data['player_name'].strip()

    def clean_email(self):
        return self.cleaned_data['email'].strip()

    def clean_gamer_tag(self):
        return self.cleaned_data['gamer_tag'].strip()

    def clean_phone_number(self):
        return self.cleaned_data['phone_number'].strip()

proleague/templates/proleague/game_detail.html
{% extends 'proleague/base.html' %}

{% block title %}
    Game - {{ game }}
{% endblock %}

{% block content %}
    <article>
        <div class="row">
            <div class="offset-by-two eight columns">
                <h2>{{ game }}</h2>
                <ul class="inline">
                {% if perms.proleague.change_game %}
                    <li>
                        <a href="{{ game.get_update_url }}" class="button button-primary">
                            Edit Game
                        </a>
                    </li>
                {% endif %}
                {% if perms.proleague.delete_game %}
                    <li>
                        <a href="{{ game.get_delete_url }}" class="button button-primary">
                            Delete Game
                        </a>
                    </li>
                {% endif %}
                </ul>
                <section>
                    <table>
                        <tr>
                            <th>Game Name:</th>
                            <td>
                                <a href="{{ game.website }}" target="_blank" rel="noopener noreferrer">
                                    {{ game.game_name }}
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <th>Genre:</th>
                            <td>{{ game.genre }}</td>
                        </tr>
                        <tr>
                            <th>Developer:</th>
                            <td>
                                <a href="{{ game.developer_website }}" target="_blank" rel="noopener noreferrer">
                                    {{ game.developer }}
                                </a>
                            </td>
                        </tr>
                    </table>
                </section>

                <section>
                    <h3>Tournaments</h3>
                    <ul>
                    {% for tournament in tournament_list %}
                        <li>
                            <a href="{{ tournament.get_absolute_url }}">{{ tournament }}</a>
                        </li>
                    {% empty %}
                        <li><em>There are currently no tournaments for this game.</em></li>
                    {% endfor %}
                    </ul>
                </section>
            </div>
        </div> <!-- row -->
    </article>
{% endblock %}

proleague/templates/proleague/game_form_update.html
{% extends 'proleague/base.html' %}

{% block title %}
    Update Game
{% endblock %}

{% block content %}
    <form action="{{ game.get_update_url }}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
        <button type="submit" class="button button-primary">Update Game</button>
    </form>
{% endblock %}

proleague/templates/proleague/game_list.html
{% extends 'proleague/base.html' %}

{% block title %}
    Game List
{% endblock %}

{% block create_button %}
    {% if perms.proleague.add_game %}
        <a href="{% url 'proleague_game_create_urlpattern' %}" class="button button-primary">
            Create New Game
        </a>
    {% endif %}
{% endblock %}

{% block org_content %}
    <h2>Game List</h2>
    <ul>
    {% for game in game_list %}
        <li>
            <a href="{{ game.get_absolute_url }}">
                {{ game }}
            </a>
        </li>
    {% empty %}
        <li><em>There are currently no games available.</em></li>
    {% endfor %}
    </ul>
{% endblock %}

proleague/templates/proleague/match_form_update.html
{% extends 'proleague/base.html' %}

{% block title %}
    Update Match
{% endblock %}

{% block content %}
    <form action="{{ match.get_update_url }}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
        <button type="submit" class="button button-primary">Update Match</button>
    </form>
{% endblock %}

proleague/templates/proleague/password_change_done.html
{% extends 'proleague/base.html' %}

{% block title %}
    Change Password Successful
{% endblock %}

{% block content %}
    <div>
        <h2>Change Password Successful!</h2>
        <p>
            You have changed your password!
        </p>
        <p>
            Return to <a href="{% url 'login_urlpattern' %}">Log In</a>.
        </p>
    </div>
{% endblock %}

proleague/templates/proleague/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

proleague/templates/proleague/password_reset_form.html
{% extends 'proleague/base.html' %}

{% block title %}Reset Password{% endblock %}

{% block content %}
    <h2>Reset Password</h2>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
        <button type="submit" class="button button-primary">
    	    Send Confirmation Link
        </button>
    </form>
{% endblock %}

proleague/templates/proleague/school_list.html
{% extends 'proleague/base.html' %}

{% block title %}
    School List
{% endblock %}

{% block create_button %}
    {% if perms.proleague.add_school %}
        <a href="{% url 'proleague_school_create_urlpattern' %}" class="button button-primary">
            Create New School
        </a>
    {% endif %}
{% endblock %}

{% block org_content %}
    <h2>School List</h2>
    <ul>
    {% for school in school_list %}
        <li>
            <a href="{{ school.get_absolute_url }}">
                {{ school }}
            </a>
        </li>
    {% empty %}
        <li><em>There are currently no schools available.</em></li>
    {% endfor %}
    </ul>
{% endblock %}

proleague/templates/proleague/team_confirm_delete.html
{% extends 'proleague/base.html' %}

{% block title %}
    Delete Team
{% endblock %}

{% block content %}
    <form action="{{ team.get_delete_url }}" method="post">
    {% csrf_token %}
        <p>
            Are you sure that you want to delete
            team {{ team }}?
        </p>
        <a href="{{ team.get_absolute_url }}" class="button button-primary">
            Cancel
        </a>
        <button type="submit" class="button button-primary">Delete Team</button>
    </form>
{% endblock %}

proleague/templates/proleague/team_detail.html
{% extends 'proleague/base.html' %}

{% block title %}
    Team - {{ team }}
{% endblock %}

{% block content %}
    <article>
        <div class="row">
            <div class="offset-by-two eight columns">
                <h2>{{ team }}</h2>
                <ul class="inline">
                {% if perms.proleague.change_team %}
                    <li>
                        <a href="{{ team.get_update_url }}" class="button button-primary">
                            Edit Team
                        </a>
                    </li>
                {% endif %}
                {% if perms.proleague.delete_team %}
                    <li>
                        <a href="{{ team.get_delete_url }}" class="button button-primary">
                            Delete Team
                        </a>
                    </li>
                {% endif %}
                </ul>
                <section>
                    <table>
                        <tr>
                            <th>Team Name:</th>
                            <td>{{ team.team_name }}</td>
                        </tr>
                        <tr>
                            <th>Acronym:</th>
                            <td>{{ team.acronym }}</td>
                        </tr>
                        <tr>
                            <th>Tournament:</th>
                            <td><a href="{{ tournament.get_absolute_url }}">{{ tournament }}</a></td>
                        </tr>
                        {% if position %}
                        <tr>
                            <th>Position:</th>
                            <td>{{ position }}</td>
                        </tr>
                        {% endif %}
                    </table>
                </section>

                <section>
                    <h3>Players</h3>
                    <ul>
                    {% for player in player_list %}
                        <li>
                            <a href="{{ player.get_absolute_url }}">{{ player }}</a>
                        </li>
                    {% empty %}
                        <li><em>There are currently no players for this team.</em></li>
                    {% endfor %}
                    </ul>
                </section>

                <section>
                    <h3>Matches</h3>
                    <ul>
                    {% for match in match_list %}
                        <li>
                            <a href="{{ match.get_absolute_url }}">{{ match }}</a>
                        </li>
                    {% empty %}
                        <li><em>There are currently no matches for this team.</em></li>
                    {% endfor %}
                    </ul>
                </section>
            </div>
        </div> <!-- row -->
    </article>
{% endblock %}

proleague/templates/proleague/team_form_update.html
{% extends 'proleague/base.html' %}

{% block title %}
    Update Team
{% endblock %}

{% block content %}
    <form action="{{ team.get_update_url }}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
        <button type="submit" class="button button-primary">Update Team</button>
    </form>
{% endblock %}

proleague/templates/proleague/team_refuse_delete_players.html
{% extends 'proleague/base.html' %}

{% block title %}
    Error Deleting Team
{% endblock %}

{% block content %}
    <div>
        <h2>Error Deleting Team</h2>
        <p>
            You may not delete team {{ team }}. This
            team currently has the following
            players:
        </p>

        <ul>
        {% for player in players %}
            <li><a href="{{ player.get_absolute_url }}">{{ player }}</a></li>
        {% endfor %}
        </ul>

        <p>
            Return to <a href="{% url 'proleague_team_list_urlpattern' %}">Team List</a>.
        </p>
    </div>
{% endblock %}

proleague/templates/proleague/tournament_detail.html
{% extends 'proleague/base.html' %}

{% block title %}
    Tournament - {{ tournament }}
{% endblock %}

{% block content %}
    <article>
        <div class="row">
            <div class="offset-by-two eight columns">
                <h2>{{ tournament }}</h2>
                <ul class="inline">
                {% if perms.proleague.change_tournament %}
                    <li>
                        <a href="{{ tournament.get_update_url }}" class="button button-primary">
                            Edit Tournament
                        </a>
                    </li>
                {% endif %}
                {% if perms.proleague.delete_tournament %}
                    <li>
                        <a href="{{ tournament.get_delete_url }}" class="button button-primary">
                            Delete Tournament
                        </a>
                    </li>
                {% endif %}
                </ul>
                <section>
                    <table>
                        <tr>
                            <th>Tournament Name:</th>
                            <td>{{ tournament.tournament_name }}</td>
                        </tr>
                        <tr>
                            <th>Start Date:</th>
                            <td>{{ tournament.start_date }}</td>
                        </tr>
                        <tr>
                            <th>End Date:</th>
                            <td>{{ tournament.end_date }}</td>
                        </tr>
                        <tr>
                            <th>Game:</th>
                            <td><a href="{{ game.get_absolute_url }}">{{ game }}</a></td>
                        </tr>
                    </table>
                </section>

                <section>
                    <h3>Teams</h3>
                    <ul>
                        <h5>1st Place</h5>
                        {% for team in team_list %}
                            {% if team.position.position_sequence == 1 %}
                                <li>
                                    <a href="{{ team.get_absolute_url }}">{{ team }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        <h5>2nd Place</h5>
                        {% for team in team_list %}
                            {% if team.position.position_sequence == 2 %}
                                <li>
                                    <a href="{{ team.get_absolute_url }}">{{ team }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        <h5>3rd - 4th Place</h5>
                        {% for team in team_list %}
                            {% if team.position.position_sequence == 3 %}
                                <li>
                                    <a href="{{ team.get_absolute_url }}">{{ team }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        <h5>5th - 8th Place</h5>
                        {% for team in team_list %}
                            {% if team.position.position_sequence == 4 %}
                                <li>
                                    <a href="{{ team.get_absolute_url }}">{{ team }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        <h5>9th - 16th Place</h5>
                        {% for team in team_list %}
                            {% if team.position.position_sequence == 5 %}
                                <li>
                                    <a href="{{ team.get_absolute_url }}">{{ team }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    {% for team in team_list %}
                    {% empty %}
                        <li><em>There are currently no teams for this tournament.</em></li>
                    {% endfor %}
                    </ul>
                </section>
            </div>
        </div> <!-- row -->
    </article>
{% endblock %}